### ISSUE TITLE
Only Windows

### ISSUE THREAD

**Issue by Pzre9** [jozews321/T430-Hackintosh-Opencore#11]
After I followed the guide, it seems like there is only one boot entry in OpenCore, which is literally Windows. Any solutions to appear the macOS Boot Recovery boot entry?

**Comment by jozews321** [comment]
I'm gonna need some more info to be able to help.
Have you tried to press the space key to show the hidden OC options?

**Comment by Pzre9** [comment]
No. I haven't.

**Comment by Pzre9** [comment]
Oh, I found it. Thanks m8
