### ISSUE TITLE
Optimizing CPU power management (Step from readme)

### ISSUE THREAD

**Issue by jhay06** [jozews321/T430-Hackintosh-Opencore#12]
Hi , just want to ask do we need to do this step or it is already included on efi ? 

thanks

**Comment by jozews321** [comment]
You need to do it it's specific to your model of CPU

**Comment by jhay06** [comment]
enabling cpupm and cpuoist in Delete /Drop cause the mac not boot, so i can't continue to ssdgen

**Comment by WilfredoMT** [comment]
add -v to boot-args and send me a photo or something

**Comment by jozews321** [comment]
Add -v to boot-args and send me a photo or something

**Comment by jhay06** [comment]
i'm sorry i wasn't able to attend on this , will try to do it this weekends thank you
