### ISSUE TITLE
"Super Slow and then Stuck" kind of Startup.

### ISSUE THREAD

**Issue by Pzre9** [jozews321/T430-Hackintosh-Opencore#13]
Hey there, it's me again. After I done everything and booted in the OC Bootloader, at first, the bar went okay, then it started to slow down, and then it just stayed stuck there. Do you know any solutions to solve it? (PS: I was installing macOS Monterey)

**Comment by jozews321** [comment]
Add `-v` to boot-args in the config.plist to see where do you get stuck and send a picture or something

**Comment by Pzre9** [comment]
Oh, I just founded out that the error is just "Frozen in macOS Installer after 30s". (man, i should look at manuals first)
