### ISSUE TITLE
Actual Bug

### ISSUE THREAD

**Issue by Pzre9** [jozews321/T430-Hackintosh-Opencore#14]
<img width="2204" alt="11-boot b02845ce" src="https://github.com/jozews321/T430-Hackintosh-Opencore/assets/105113599/135b4188-b3b7-4a65-91d3-7f00b7493f01">
Ok, the actual bug here is OpenCore freezing at the Apple logo after some time. Do you know how to resolve it? (PS: Here's a picture to give you more clarification):
(PS2: BTW, I took this picture from OpenCore so that is why there's a cursor up there, mine though didn't.)

**Comment by rastiqdev** [comment]
What version are you trying to run? If you are trying to run Monterey or lower, you can just use the first version of the EFI which weirdly works better.

**Comment by hqnicolas** [comment]
same here, 
on T430 OpenCore 0.9.2 - v2.0.0
I can enable the Verbose, and see it Stuck at "apfs module start"
on T430 OpenCore 0.9.2 - v2.1.1
I can't enable the Verbose

**Comment by hqnicolas** [comment]
To solve @Pzre9 problem and mine
i take the 0.7.9 T430-Hackintosh-v1 Release USBMap.kext and USBMapLegacy.kext
and ADD kext on T430 OpenCore 0.9.2 - **v2.1.1** config.plist
		
                 	<dict>
				<key>BundlePath</key>
				<string>USBMap.kext</string>
				<key>Comment</key>
				<string>USBMap.kext</string>
				<key>Enabled</key>
				<true/>
				<key>ExecutablePath</key>
				<string></string>
				<key>Arch</key>
				<string>Any</string>
				<key>MaxKernel</key>
				<string></string>
				<key>MinKernel</key>
				<string>19.00.00</string>
				<key>PlistPath</key>
				<string>Contents/Info.plist</string>
			</dict>

You can mark it down as SOLVED!
Tested on Olarila's MacOS 12.6.8 Monterey 
after install, use the regular config.plist
