### ISSUE TITLE
No Wi-Fi and USB devices not working on macOS Big Sur

### ISSUE THREAD

**Issue by rastiqdev** [jozews321/T430-Hackintosh-Opencore#15]
Hello, 

I installed the latest version of macOS Big Sur (11.7.8) successfully with Olarila's offline installer image but I realised there was no Wi-Fi, and when I switched to the Post-Install configuration, my USB devices (mouse) wouldn't work anymore. This is pretty weird because on an older version of the EFI (on which I currently am), the Wi-Fi works perfectly and my mouse too. 

After reading the config.plist's contents, I realised that the Wi-Fi issue may be caused by the fact that AirportItlwm is only present on the EFI for macOS Monterey and Ventura. However, for the USB devices, I don't know how to fix the issue.

Any help would be appreciated.

**Comment by hqnicolas** [comment]
thy this peace of crap here
https://github.com/hqnicolas/Thinkpad-T430-s-OpenCorteBootloader/releases/tag/T430-Opencore

**Comment by jozews321** [comment]
Don't use Olarilla or random images, make a vanilla install first
