### ISSUE TITLE
Sonoma Possible ?

### ISSUE THREAD

**Issue by jhay06** [jozews321/T430-Hackintosh-Opencore#16]
Hoping that our device can support Sonoma in its public release on September 26th thank you

**Comment by WilfredoMT** [comment]
Yes it's very possible, I'm gonna be updating the EFI when Sonoma releases

**Comment by jozews321** [comment]
Yes I'm gonna be releasing a new update when Sonoma releases

**Comment by jhay06** [comment]
hi , sonoma is now available and our device is getting a notification for Sonoma . have you already tried to update it using Software update ? 
![image](https://github.com/jozews321/T430-Hackintosh-Opencore/assets/5191437/303483af-6a0a-436b-b608-6ef6154f6851)

since i used this T430 hackintosh in developing ios app i cannot take a risk on this so im waiting if someone tried it. thanks

**Comment by jozews321** [comment]
Wait for the EFI update

**Comment by NCVIDevASD** [comment]
i see , will wait for the latest efi thank you ,

**Comment by jhay06** [comment]
i see, will wait for the latest EFI thank you

**Comment by jozews321** [comment]
The EFI is out

**Comment by jhay06** [comment]
what is the correct flow when updating thru OTA? update then change EFI . or Efi then update?

**Comment by jozews321** [comment]
Change the EFI first and if it boots Ventura fine do the OTA

**Comment by jhay06** [comment]
btw i repeat the process , but this time i installed ventura i skip monterey , and now updating to sonoma 14.4.1 failed after OTA download all the files, during preparation it says that there's an error regarding internet ? ,
