### ISSUE TITLE
Infinte loop after installing graphic via OCLP

### ISSUE THREAD

**Issue by jhay06** [jozews321/T430-Hackintosh-Opencore#19]
i tried to update to sonoma using the new EFI and put my MLB SYSTEM UID and other information from my old plist to new plist . update is successful but after installing graphic drivers via OCLP . it doesnt boot anymore . and just loop on blackscreen with message . 
cant upload video

https://drive.google.com/file/d/1ArpRcpcYj08e3yfm1fzr94L_JDfPSx2t/view?usp=sharing

**Comment by jozews321** [comment]
What version of OCLP are you using to patch?

**Comment by jhay06** [comment]
i used the one that already exist when i was in ventura , is there any way to revert the installed graphic drivers  so i can update the OCLP then patch it again ?

**Comment by jozews321** [comment]
Patching for Sonoma is only supported in OCLP 1.0.0+. You didn't read the notes on the release of the EFI. 
You can add -igfxvesa to your boot-args to revert the root patches. Don't forget to remove the flag after that

**Comment by jhay06** [comment]
i see , ithink  i mislook due to excitement heheh , will try thanks

**Comment by jhay06** [comment]
i tried the igfxvesa but it boots to recovery image

**Comment by jhay06** [comment]
okay i got it when i put -igfxvesa in front of other parameters , then i try several restart before it continues to mac .  it odds that i get several kernel panic then several restarts before i can get a successful boot

Update: i already tried updating OCLP with 1.0.1 then remove existing patch 0.6.7 then run again the post patch , but when rebooting and then done on POST messages /kernel loading and booting messages , the screen goes gray and just stay there but the drive light still blinking , i bet i get the same error from the video i sent . but this time there's no logs it just a gray screen with drive activity

**Comment by jhay06** [comment]
if i will reinstall Mac OS can i use the same EFI ? or should i need to do the method we use in installing ventura ,? EFI in install is different in post install ?

**Comment by jozews321** [comment]
Yes you can reinstall Sonoma like normal and them patch using OCLP 1.0.0

**Comment by jhay06** [comment]
anyway to use the default recovery to reinstall Sonoma? it seems that the option reinstall is not working .

**Comment by jhay06** [comment]
will close this issue as it already fixed the main issue thanks

**Comment by jhay06** [comment]
hope that our device can still support future mac version . thank you
