### ISSUE TITLE
Stuck when booting (T430s) 

### ISSUE THREAD

**Issue by Vinnie1889** [jozews321/T430-Hackintosh-Opencore#22]
Hi there, I have the Lenovo t430s with a working opencore (Mac OS 10.15.7) 

I have trying your EFI but it doesn’t boot.
I have added -v in boot-args and its sayings something about Ethernet… 

the startup shime works, and the bootloader also. 
Can you help me? 

![IMG_1008](https://github.com/jozews321/T430-Hackintosh-Opencore/assets/149567944/528ea348-26fa-4da5-a66c-61112bdeb7c0)

![IMG_1007](https://github.com/jozews321/T430-Hackintosh-Opencore/assets/149567944/40359a1d-d90c-4b81-924d-874fc5f26422)

**Comment by WilfredoMT** [comment]
Are you sure that catalina install is vanilla? I see that you are using olarila, those images are a total mess and now supported by anyone. try to to a clean install following the guide in this repo

**Comment by jozews321** [comment]
Are you sure that catalina install is vanilla?, I see that you are using images from olarila, don't do that as they are a complete mess and unsupported by everyone. try to make a proper install following the guide on this repo

**Comment by Vinnie1889** [comment]
> Are you sure that catalina install is vanilla?, I see that you are using images from olarila, don't do that as they are a complete mess and unsupported by everyone. try to make a proper install following the guide on this repo 

Is it possible to install Catalina (vanilla) and upgrade to sonoma? 
Wil this work? I know only the basics to install Mac OS openecore.

**Comment by jozews321** [comment]
Yes it's possible to update the installation, also keep in mind that you are using a t430s, it's not exactly the same as the t430

**Comment by Vinnie1889** [comment]
> Yes it's possible to update the installation, also keep in mind that you are using a t430s, it's not exactly the same as the t430

Thanks for advice 👌
