### ISSUE TITLE
Booting problems t430s

### ISSUE THREAD

**Issue by Vinnie1889** [jozews321/T430-Hackintosh-Opencore#24]
**FIXED**
I have added SSDT-AWAC.aml in EFI\OC\ACPI 

Hi, I have still have boot issues... I have done everything right, and now it's getting stuck with a ps2 or voodoo. 

I have almost the same specs as you, and I have also ivyra1n bios. 

Is it possible you make an update in EFI? The opencore bootpicker works fine, I have sound at startups etc. 

It's really frustrating, I don't know what I do wrong 😑![image](https://github.com/jozews321/T430-Hackintosh-Opencore/assets/149567944/4527a783-b2ec-4c23-b9c4-d7d214861a5d)

**Comment by WilfredoMT** [comment]
Thanks for figuring that out! I'll add a note for T430s users

**Comment by jozews321** [comment]
Thanks for figuring that out! I'll add a note for T430s users
