### ISSUE TITLE
Split screen after installing the opencore legacy patcher

### ISSUE THREAD

**Issue by leotuxbr** [jozews321/T430-Hackintosh-Opencore#3]
Hi guys,
I got the split screen after installing the opencore legacy patcher. Does anyone know what can it be?

[[](url)](https://ibb.co/JdwX0HS)

**Comment by jozews321** [comment]
Hey I don't know if you were able to solve it. but you probably have the 768p version of the T430, you need to change the config.plist/DeviceProperties to the 768p config
