### ISSUE TITLE
Ventura Please

### ISSUE THREAD

**Issue by jhay06** [jozews321/T430-Hackintosh-Opencore#4]
The title says it all :) thanks 

hope there's a ventura version thanks , or instruction to upgrade from monterey to ventura

**Comment by jozews321** [comment]
Hi, yes I'm gonna be updating everything to support ventura

**Comment by jhay06** [comment]
thanks , i would love to see ventura working in our laptop thanks :) 
btw, would you know why the system report shows only 1 processor and 2 cpu ? 
in windows from task manager it shows 2 cpu 2 threads ,

**Comment by NCVIDevASD** [comment]
any update for ventura :) thanks

**Comment by jozews321** [comment]
Send a screenshot of the system report.

Also the new EFI for Ventura has been released!

**Comment by jhay06** [comment]
hi i try to install using recovery   but no working . no internet

Cant connect via wifi no hotspot detected 
Used lan cable but there still no internet even i update IP address and dns via scutil also added route default gw . but no luck

can you add instruction on how can i install ventura using system update from monterey ? thank you very much

**Comment by WilfredoMT** [comment]
You can update like normal from system preferences

**Comment by jozews321** [comment]
You can update like normal from Monterey

**Comment by jhay06** [comment]
hi @jozews321  how  ? , i tried to update my config.plist to "install only config.plist" from the repo and update kext file then my existing monterey doesn't boot, just stucked in black with text  ,
