### ISSUE TITLE
Better battery life on a different SMBIOS

### ISSUE THREAD

**Issue by filipemsilv4** [jozews321/T430-Hackintosh-Opencore#5]
Hi guys,

I'm just curious, is there a reason for choosing MacBookPro12,1 SMBIOS instead of MacBookPro10,2 which is an Ivy Bridge model? I saw significantly lower clock speeds in IDLE when using 10,2, the battery life is also better. Unfortunatelly the bluetooth stops working for me, but i don't think that this can be caused by the SMBIOS change (please correct me if i'm wrong).

**Comment by jozews321** [comment]
Hi, yes the EFI provided is very outdated. in the next days I'm gonna be updating it with Ventura support and better power management
