### ISSUE TITLE
Is it just me or is Ventura performing poorly?

### ISSUE THREAD

**Issue by filipemsilv4** [jozews321/T430-Hackintosh-Opencore#6]
The performance was fine on Monterey, then I updated to Ventura and now it's terrible (maybe I should do a clean install, but i want to know if anyone is experiencing the same thing first, because if so, I may choose to not use Ventura at all).

The boot time is very long and everything is slow, I tested the SSD speeds and they seem fine, also there's nothing using too much CPU or RAM, and the GeekBench score is the same as Monterey, but the system feel like it's running on an old HDD.

**Comment by jozews321** [comment]
Did you patched the system with OCLP?, performance seems to be the around the same for me

**Comment by filipemsilv4** [comment]
> Did you patched the system with OCLP?, performance seems to be the around the same for me 

Yes, I patched it with OCLP, it isn't an graphics acceleration problem. Good to know that you aren't having performance problems. I'm going to do a clean install.

**Comment by filipemsilv4** [comment]
A clean install did the trick, sorry for the bloat.
