### ISSUE TITLE
Some apps are crashing on startup

### ISSUE THREAD

**Issue by filipemsilv4** [jozews321/T430-Hackintosh-Opencore#7]
Hey, I noticed that some apps are crashing (Arc Browser and Zoom Meetings (only when entering the meeting). Do you know what can cause this? I tried reverting the OCLP Patch, but it doesn't seems to be the culprit.

Arc crash log: 
[Arc crash log.txt](https://github.com/jozews321/T430-Hackintosh-Opencore/files/11548931/Arc.crash.log.txt)

**Comment by jozews321** [comment]
Zoom meetings are working fine for me, maybe try to update your client and give the app the proper permissions in settings. I can't test Arc as they seem to be doing some invite only system

**Comment by jhay06** [comment]
i experienced this when i install mac on an HDD drive.

**Comment by filipemsilv4** [comment]
> i experienced this when i install mac on an HDD drive. 

Well, I'm using an SSD, but the problem probably isn't the disk.

**Comment by filipemsilv4** [comment]
> Zoom meetings are working fine for me, maybe try to update your client and give the app the proper permissions in settings. I can't test Arc as they seem to be doing some invite only system 

Good to know that you aren't experiencing the same issue, I'll try to reinstall the system and see if it solves it. I'd give you an invite for Arc, but, well, the browser isn't opening right now.

**Comment by jozews321** [comment]
Check this, https://github.com/jslegendre/tccplus, permissions are broken in our machines because amfi must be disabled and probably they are not applying

**Comment by filipemsilv4** [comment]
> Check this, https://github.com/jslegendre/tccplus, permissions are broken in our machines because amfi must be disabled and probably they are not applying 

Why does amfi needs to be disabled and why this wasn't an issue on Monterey?

**Comment by jozews321** [comment]
Pretty much me being lazy and having just one config for 10.13 to 13.4. amfi being disabled is only a must on 13.3+. And also that is no longer the case with the lasted beta of OCLP. I'm gonna do some testing and release a new update tomorrow with amfi enabled for everything

**Comment by filipemsilv4** [comment]
> Pretty much me being lazy and having just one config for 10.13 to 13.4. amfi being disabled is only a must on 13.3+. And also that is no longer the case with the lasted beta of OCLP. I'm gonna do some testing and release a new update tomorrow with amfi enabled for everything 

I tried installing the latest OCLP beta, but I still can't boot with amfi enabled. Did you have any success with it? I'm thinking of doing a clean install of 13.3 (or 13.2? I'm not sure which version is the adequate) since it doesn't require disabling amfi.

**Comment by jozews321** [comment]
Hi, I tested the new patches without disabling amfi. and also fixed the issue of apps crashing (it wasn't related to amfi after all). I'm gonna be updating soon

**Comment by filipemsilv4** [comment]
> Hi, I tested the new patches without disabling amfi. and also fixed the issue of apps crashing (it wasn't related to amfi after all). I'm gonna be updating soon 

After all, what was causing apps to crash?

**Comment by jozews321** [comment]
> > Hi, I tested the new patches without disabling amfi. and also fixed the issue of apps crashing (it wasn't related to amfi after all). I'm gonna be updating soon
> 
> After all, what was causing apps to crash?

Some issue introduced in macOS 13.3 that was using AVX2 code paths for some system stuff. For context our CPUs don't support AVX2 at all, so with an update to the RestrictEvents Kexts it is possible to patch out the AVX2 stuff

**Comment by filipemsilv4** [comment]
> > > Hi, I tested the new patches without disabling amfi. and also fixed the issue of apps crashing (it wasn't related to amfi after all). I'm gonna be updating soon
> > 
> > After all, what was causing apps to crash?
> 
> Some issue introduced in macOS 13.3 that was using AVX2 code paths for some system stuff. For context our CPUs don't support AVX2 at all, so with an update to the RestrictEvents Kexts it is possible to patch out the AVX2 stuff

Oh, updating the kext solved the issue for Arc. Nice!
