### ISSUE TITLE
Monterey - Ventura [Updating]

### ISSUE THREAD

**Issue by jhay06** [jozews321/T430-Hackintosh-Opencore#8]
Hi , sorry my other issue was closed recently and i understand it , because the title is for request for ventura , and technically its done . 

so i created another one with new title 

Okay , i have existing monterey , then downloaded the updated efi for Ventura support , update my EFI then use the "install only" config.plist first thinking that when i use this config i can just dowload the update from update manager , 

okay so i updated the efi , then reboot 

after reboot my monterey is not booting anymore it just stuck in black

any ideas ? thanks

**Comment by jozews321** [comment]
Can you show me where it gets stuck. Also switch to the post install config.plist too

**Comment by jhay06** [comment]
this is where it stuck. i beleive the post install is macbookpro 10,1 that is my current efi config as per tonymacx86 . it doesnt show ventura update
![image20230525_184536896](https://github.com/jozews321/T430-Hackintosh-Opencore/assets/5191437/4b4454d3-dab8-4c8a-8672-a999eedd6076)

**Comment by filipemsilv4** [comment]
Not what you asked for, but I recommend doing a clean install, I got awful performance by just updating.

**Comment by jhay06** [comment]
i try the clean install but i cant get wifi working . i tried also the ethernet cable but connecting with ethernet cable got a fixed wrong ip . 11.X.X.X my server is 192.168 so i changed the ip using ifconfig and change default gw and change the dns . but still cant get the internet working

**Comment by filipemsilv4** [comment]
> i try the clean install but i cant get wifi working . i tried also the ethernet cable but connecting with ethernet cable got a fixed wrong ip . 11.X.X.X my server is 192.168 so i changed the ip using ifconfig and change default gw and change the dns . but still cant get the internet working 

Do you have the stock WiFi card? (Centrino 6205-N)

**Comment by jhay06** [comment]
yes . infact its working in my current version of mac . monterey

**Comment by filipemsilv4** [comment]
> yes . infact its working in my current version of mac . monterey

Check if Airportitlwm13 kext (or something like that) is enabled on Ventura. If you're using the same EFI for Monterey and Ventura, and Wifi works only on Monterey, it's possible that Airportitlwm12 is enabled and Airportitlwm13 is not.

**Comment by jhay06** [comment]
im using the updated efi from the releases . i believed its already set up . but will check also thanks

**Comment by jhay06** [comment]
i can confirm that airportitlwm13 is loaded but not working from installer gui. so i try to download offline full installer ventura 13.4 it successfully install with installonly but cant proceed on the setup changing it to postinstall config doesnt fix it. when gui enter to choose the country the mac suddenly goes gray screen then black screen telling that the system will shutdown.

**Comment by filipemsilv4** [comment]
> i can confirm that airportitlwm13 is loaded but not working from installer gui. so i try to download offline full installer ventura 13.4 it successfully install with installonly but cant proceed on the setup changing it to postinstall config doesnt fix it. when gui enter to choose the country the mac suddenly goes gray screen then black screen telling that the system will shutdown.

I got this problem on the "choose country" screen too. You need to use the installation config in this part and only change to the postinstall config after you get to the desktop.

**Comment by jozews321** [comment]
Airportitlwm is very buggy in Ventura, even more in the recovery OS. I would advice to use ethernet or Android tethering 
Edit: It seems that they released a new update to address the wifi networks not showing up. It's going to be included In the next release

**Comment by jhay06** [comment]
i cant continue to setup ventura 13.4 when select country shows up the screen it suddenly greyed out then black screen with logs then reboot . 


i tried also to install version 13 official release but i have a problem in completing the installation . it always show error failed updating the system .

what specific version of ventura works?

**Comment by jhay06** [comment]
> > i can confirm that airportitlwm13 is loaded but not working from installer gui. so i try to download offline full installer ventura 13.4 it successfully install with installonly but cant proceed on the setup changing it to postinstall config doesnt fix it. when gui enter to choose the country the mac suddenly goes gray screen then black screen telling that the system will shutdown.
> 
> I got this problem on the "choose country" screen too. You need to use the installation config in this part and only change to the postinstall config after you get to the desktop.

actually i experience the same behavior with install only and post install . what version og ventura you used?

**Comment by filipemsilv4** [comment]
> > > i can confirm that airportitlwm13 is loaded but not working from installer gui. so i try to download offline full installer ventura 13.4 it successfully install with installonly but cant proceed on the setup changing it to postinstall config doesnt fix it. when gui enter to choose the country the mac suddenly goes gray screen then black screen telling that the system will shutdown.
> > 
> > I got this problem on the "choose country" screen too. You need to use the installation config in this part and only change to the postinstall config after you get to the desktop.
> 
> actually i experience the same behavior with install only and post install . what version og ventura you used?

I've used 13.4

**Comment by jhay06** [comment]
i managed to install now the 13 official release i just plugged the lan and then the error disappear,  but the wifi is not working when i switched to postinstall config,  but from the installonly config . the wifi works


what is the difference between this 2 config?


ventura doesnt have problems in install config . i just retain the installonly config even after installl everything seems working fine. postinstall config wifi doesnt work 

privacy and security doesnt work i try to use zoom but cannot find the microphone access request from privacy and security

**Comment by filipemsilv4** [comment]
> i managed to install now the 13 official release i just plugged the lan and then the error disappear,  but the wifi is not working when i switched to postinstall config,  but from the installonly config . the wifi works
> 
> 
> what is the difference between this 2 config?
> 
> 
> ventura doesnt have problems in install config . i just retain the installonly config even after installl everything seems working fine. postinstall config wifi doesnt work 
> 
> privacy and security doesnt work i try to use zoom but cannot find the microphone access request from privacy and security 

Since amfi is disabled, you'll need tccplus in order to give permissions.

**Comment by jozews321** [comment]
A just released a new update, the intel wifi should work in Ventura much more reliably

**Comment by jhay06** [comment]
> A just released a new update, the intel wifi should work in Ventura much more reliably

doest boot . stuck on apple logo using postinstall. i just update my efi and put all my macbookpro10,1 confif on the latest config.plist   and i got stucked on apple logo

**Comment by jhay06** [comment]
![image20230528_080130776](https://github.com/jozews321/T430-Hackintosh-Opencore/assets/5191437/5e651b26-dfb0-40ad-8cb2-bfccce377f69)
do i need to clean install again?

**Comment by jozews321** [comment]
In the config.plist add -v to boot-args and send me a photo or something of where it gets stuck

**Comment by jhay06** [comment]
![image20230530_074841624](https://github.com/jozews321/T430-Hackintosh-Opencore/assets/5191437/ba30653d-0847-4f80-bfb8-970d443f3c35)

**Comment by jozews321** [comment]
It looks like a bios config is wrong, check it again and reset nvram

**Comment by jhay06** [comment]
> It looks like a bios config is wrong, check it again and reset nvram

does resetting nvram safe on thinkpad T430? i saw from opencore disclaimer that resetting nvram can damage thinkpad . i just want to confirm if is it safe on our unit?

**Comment by filipemsilv4** [comment]
> > It looks like a bios config is wrong, check it again and reset nvram
> 
> does resetting nvram safe on thinkpad T430? i saw from opencore disclaimer that resetting nvram can damage thinkpad . i just want to confirm if is it safe on our unit?

It is safe on our model. Just be careful not to lose other boot entries when resetting NVRAM.

**Comment by jhay06** [comment]
noted on that . but on the latest EFI theres no reset nvram option .

**Comment by jozews321** [comment]
Yeah it's safe. The issue with resetting NVRAM was in early bios revisions of the t480. 
Press space on the picker to reveal the NVRAM reset option

**Comment by jhay06** [comment]
done resetting but still hang
![image20230531_070722291](https://github.com/jozews321/T430-Hackintosh-Opencore/assets/5191437/1614d8c7-0819-4f61-baa8-ada9461edded)

**Comment by filipemsilv4** [comment]
I have the same problem. This wasn't happening on the previous EFI.![PXL_20230530_203507394.jpg](https://github.com/jozews321/T430-Hackintosh-Opencore/assets/59426206/8c2c4bf2-1389-490e-9437-a5d3c00c2437)

**Comment by jhay06** [comment]
i think the new efi requires us to clean install not only updating the efi

**Comment by jozews321** [comment]
Oh, with the new EFI the version 2.1.0 you need to unpatch the system using OCLP and EFI version 2.0.0 first and then use the new one

**Comment by filipemsilv4** [comment]
> Oh, with the new EFI the version 2.1.0 you need to unpatch the system using OCLP and EFI version 2.0.0 first and then use the new one 

That's what I did

**Comment by jhay06** [comment]
already done unpatching but same result

**Comment by jhay06** [comment]
any updates

**Comment by filipemsilv4** [comment]
> any updates

I haven't tried a clean install because I don't have time right now, but I bet that it will solve the issue.

**Comment by jhay06** [comment]
i can confirm that the latest efi is not working at all. i tried to clean install even i used the install only config it doesnt boot the installer . stucked in the same logs

**Comment by jozews321** [comment]
Ok noted, I will release a new one trying to address the issue. For now you can try to add `amfi=0x80` to `boot-args `

**Comment by jhay06** [comment]
> Ok noted, I will release a new one trying to address the issue. For now you can try to add `amfi=0x80` to `boot-args `

hi sir, what is this for ?  is this args is to disable amfi? thanks 

by the way in the instruction , there's a steps to do this https://dortania.github.io/OpenCore-Post-Install/universal/pm.html#ssdtprgen-troubleshooting ? 

does this steps need to do individually per device ? thanks

**Comment by jozews321** [comment]
Yes, with that you will disable amfi

**Comment by jhay06** [comment]
okay i tried the amfi=0x80 still not booting.

**Comment by jozews321** [comment]
And with the v2.0.0 EFI it boots right? Try to disable the AMFIPass kext too

**Comment by jhay06** [comment]
![image20230606_133242667](https://github.com/jozews321/T430-Hackintosh-Opencore/assets/5191437/6f6ec38d-71e5-4164-ba4d-52b78d1b9d42)


kernel panic

**Comment by jozews321** [comment]
Oh that explains a lot the power management Kexts are panicking. It's complaining about the CFG lock. Have you changed the bundled OpenCore or disabled the AppleCpuPmCfgLock quirk?

**Comment by jhay06** [comment]
no im not changing any , i just used the config and efi from the releases page

**Comment by jhay06** [comment]
any updates ? thanks

**Comment by jhay06** [comment]
hi sir any updates on this , thanks

**Comment by jozews321** [comment]
Have you used release v2.0.0?

**Comment by jhay06** [comment]
yes , im currently using it 2.0.0 because its working , but apps like android emulator , virualbox are crashing there .

**Comment by jozews321** [comment]
Also what OS version are you using?

**Comment by jhay06** [comment]
Ventura 13.4

**Comment by jozews321** [comment]
Ok I just released v2.1.1 to fix the issue. Tell me if it works now, remember unpatch your system first and then try the new release and patch with OCLP 0.6.7 amfipass beta

**Comment by jhay06** [comment]
noted thanks :)

**Comment by jhay06** [comment]
i think its working now . but should i uncheck disable AMFI from OCLP ? 
![image](https://github.com/jozews321/T430-Hackintosh-Opencore/assets/5191437/7d4a5a2d-8e13-4358-aa68-9ca2a66fc5b0)

**Comment by jhay06** [comment]
> i think its working now . but should i uncheck disable AMFI from OCLP ? ![image](https://user-images.githubusercontent.com/5191437/245090433-7d4a5a2d-8e13-4358-aa68-9ca2a66fc5b0.png)

also i can't patch OCLP , 
![image](https://github.com/jozews321/T430-Hackintosh-Opencore/assets/5191437/13624288-bddd-4fbb-bb8a-0a3379530dd6)


sorry just found out that there's really an installer opencore patcher amfipass beta 2 , but i don't know what version it is .

**Comment by jozews321** [comment]
Ignore everything but the root patches from OCLP, the other options are stuff for real macs only.
AMFI is enabled in the config, make sure you have this oclp version: https://github.com/dortania/OpenCore-Legacy-Patcher/releases/download/amfipass-beta-test/OpenCore-Patcher-amfipass-beta-2.app.zip

**Comment by jhay06** [comment]
okay , thanks , this is to confirm that this is now okay and solved , will close the issue now :) thank you very much
