### ISSUE TITLE
Monterey Issue

### ISSUE THREAD

**Issue by LHenaor** [jozews321/T430-Hackintosh-Opencore#9]
Hi:
I just Following the instruction in my Lenovo ThinkPad T430 (Core I5, 8GB Ram, 128GB SSD); after post Install process when I try to start up the machine, the computer frezze in "com.apple.appleFSCompressionTypeZlib load".  Any Ideas?

![IMG_0205](https://github.com/jozews321/T430-Hackintosh-Opencore/assets/134734449/70c28c56-26df-4d21-a3bc-ed7e7c2508f4)

**Comment by filipemsilv4** [comment]
Did you follow Dortania's guide to create the USB? I couldn't install when I tried to use an Olarilla disk image.

**Comment by LHenaor** [comment]
Yes sir, I used the Dortania's guide to create the USB.  I think that my problem is "something" in the BIOS thjat is not set correctly.

**Comment by LHenaor** [comment]
Hi Friends, My problem was solved; the problem was in the BIOS Config, What I did was restore the BIOS configuration to setup defaults; after that I set the changes indicated in the Dortanias's guide and voila!!! the Lenovo started great.

My process now is to do the after install steps and check everything is working fine.

Luisfer
